# to install this environment:
# conda env create --file environment.yaml
# or if using micromamba:
# micromamba create -f environment.yaml
name: irv-autopkg
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - irv-autopkg-client         # client API
    - datapackage                # parsing datapackage objects
    - nismod-snail               # raster-vector intersections
  - matplotlib                   # basic plotting
  - geopandas                    # geospatial dataframes
  - rasterio                     # raster operations
  - rioxarray                    # raster operations
  - ipykernel                    # notebook support
  - jupyter                      # notebook support
  - nb_conda_kernels             # notebook support
  - nbstripout                   # notebooks in git
  - flake8                       # python linter
