# to install this environment:
# conda env create --file environment.yaml
# or if using micromamba:
# umamba create -f ./environment.yaml
name: irv-autopkg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flake8 # python linter
  - geopandas # geospatial dataframes
  - ipykernel # notebook support
  - jupyter # notebook support
  - matplotlib # basic plotting
  - nb_conda_kernels # notebook support
  - nbstripout # notebooks in git
  - rasterio # raster operations
  - rioxarray # raster operations
  - tqdm
  - pip
  - pip:
      - irv-autopkg-client # client API
      - datapackage # parsing datapackage objects
      - nismod-snail # raster-vector intersections
